# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8863ba308044cd9d4092bd37cfc6da8e1215bda63bcf5db5e26d9781591eed59b110d9060d249553a65486ef48474da03c555fe80daa531722bac8ec5c86cb4

test:
  secret_key_base: 0e55482d866a6a16e9216819c146905dfd9aa89581481c0bdd6956d453df07330748c1d0e01f7d88a289585e5c82bd41a82b416b3e13c2f674b382ebc46c8bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
